# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.4-r1

EAPI=8

CRATES="
	addr2line@0.21.0
	adler@1.0.2
	aho-corasick@1.1.2
	anyhow@1.0.80
	autocfg@1.1.0
	automod@1.0.14
	backtrace@0.3.69
	base64@0.21.7
	bitflags@1.3.2
	bitflags@2.4.2
	build-alert@0.1.6
	bumpalo@3.15.4
	bytes@1.5.0
	cc@1.0.90
	cfg-if@1.0.0
	colored@2.1.0
	console@0.15.8
	core-foundation-sys@0.8.6
	core-foundation@0.9.4
	crc32fast@1.4.0
	crossbeam-deque@0.8.5
	crossbeam-epoch@0.9.18
	crossbeam-utils@0.8.19
	either@1.10.0
	encode_unicode@0.3.6
	encoding_rs@0.8.33
	equivalent@1.0.1
	errno@0.3.8
	fastrand@2.0.1
	filetime@0.2.23
	flate2@1.0.28
	fnv@1.0.7
	foreign-types-shared@0.1.1
	foreign-types@0.3.2
	form_urlencoded@1.2.1
	futures-channel@0.3.30
	futures-core@0.3.30
	futures-io@0.3.30
	futures-sink@0.3.30
	futures-task@0.3.30
	futures-util@0.3.30
	gimli@0.28.1
	h2@0.3.24
	hashbrown@0.14.3
	hermit-abi@0.3.9
	http-body@0.4.6
	http@0.2.12
	httparse@1.8.0
	httpdate@1.0.3
	hyper-tls@0.5.0
	hyper@0.14.28
	idna@0.5.0
	indexmap@2.2.5
	insta@1.36.1
	ipnet@2.9.0
	itoa@1.0.10
	js-sys@0.3.69
	lazy_static@1.4.0
	libc@0.2.153
	linked-hash-map@0.5.6
	linux-raw-sys@0.4.13
	log@0.4.21
	memchr@2.7.1
	mime@0.3.17
	miniz_oxide@0.7.2
	mio@0.8.11
	native-tls@0.2.11
	num_cpus@1.16.0
	object@0.32.2
	once_cell@1.19.0
	openssl-macros@0.1.1
	openssl-probe@0.1.5
	openssl-sys@0.9.101
	openssl@0.10.64
	percent-encoding@2.3.1
	pin-project-lite@0.2.13
	pin-utils@0.1.0
	pkg-config@0.3.30
	proc-macro2@1.0.78
	quote@1.0.35
	rayon-core@1.12.1
	rayon@1.9.0
	redox_syscall@0.4.1
	ref-cast-impl@1.0.22
	ref-cast@1.0.22
	regex-automata@0.4.6
	regex-syntax@0.8.2
	regex@1.10.3
	reqwest@0.11.24
	rustc-demangle@0.1.23
	rustix@0.38.31
	rustls-pemfile@1.0.4
	rustversion@1.0.14
	ryu@1.0.17
	same-file@1.0.6
	schannel@0.1.23
	security-framework-sys@2.9.1
	security-framework@2.9.2
	serde@1.0.197
	serde_derive@1.0.197
	serde_json@1.0.114
	serde_urlencoded@0.7.1
	similar@2.4.0
	slab@0.4.9
	socket2@0.5.6
	syn-test-suite@0.0.0+test
	syn@2.0.52
	sync_wrapper@0.1.2
	system-configuration-sys@0.5.0
	system-configuration@0.5.1
	tar@0.4.40
	tempfile@3.10.1
	termcolor@1.4.1
	tinyvec@1.6.0
	tinyvec_macros@0.1.1
	tokio-native-tls@0.3.1
	tokio-util@0.7.10
	tokio@1.36.0
	tower-service@0.3.2
	tracing-core@0.1.32
	tracing@0.1.40
	try-lock@0.2.5
	unicode-bidi@0.3.15
	unicode-ident@1.0.12
	unicode-normalization@0.1.23
	url@2.5.0
	vcpkg@0.2.15
	walkdir@2.5.0
	want@0.3.1
	wasi@0.11.0+wasi-snapshot-preview1
	wasm-bindgen-backend@0.2.92
	wasm-bindgen-futures@0.4.42
	wasm-bindgen-macro-support@0.2.92
	wasm-bindgen-macro@0.2.92
	wasm-bindgen-shared@0.2.92
	wasm-bindgen@0.2.92
	web-sys@0.3.69
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.6
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-sys@0.48.0
	windows-sys@0.52.0
	windows-targets@0.48.5
	windows-targets@0.52.4
	windows_aarch64_gnullvm@0.48.5
	windows_aarch64_gnullvm@0.52.4
	windows_aarch64_msvc@0.48.5
	windows_aarch64_msvc@0.52.4
	windows_i686_gnu@0.48.5
	windows_i686_gnu@0.52.4
	windows_i686_msvc@0.48.5
	windows_i686_msvc@0.52.4
	windows_x86_64_gnu@0.48.5
	windows_x86_64_gnu@0.52.4
	windows_x86_64_gnullvm@0.48.5
	windows_x86_64_gnullvm@0.52.4
	windows_x86_64_msvc@0.48.5
	windows_x86_64_msvc@0.52.4
	winreg@0.50.0
	xattr@1.3.1
	yaml-rust@0.4.5
"

inherit cargo

DESCRIPTION="Parser for Rust source code"
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/dtolnay/syn"
SRC_URI="${CARGO_CRATE_URIS}"

# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="0BSD Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD Boost-1.0 ISC MIT MPL-2.0 Unicode-DFS-2016 Unlicense ZLIB"
SLOT="0"
RESTRICT="test"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND="
	${DEPEND}
	virtual/rust
"
BDEPEND=""

# rust does not use *FLAGS from make.conf, silence portage warning
# update with proper path to binaries this crate installs, omit leading /
QA_FLAGS_IGNORED="usr/bin/${PN}"

src_unpack() {
	default
	cargo_src_unpack
}

src_configure() {
	cargo_src_configure
}

src_compile() {
	cargo_src_compile
}

src_test() {
	ecargo test --all-features
}

src_install() {
	cargo_src_install
}
